---
- name: "Retrieve an access token"
  ansible.builtin.uri:
    url: "{{ imagebuilder_auth_url }}"
    method: "POST"
    body:
      grant_type: "refresh_token"
      client_id: "rhsm-api"
      refresh_token: "{{ satellite_rhsm_offline_token }}"
    body_format: "form-urlencoded"
    validate_certs: true
    return_content: true
  register: __result

- name: "Set access token"
  ansible.builtin.set_fact:
    __access_token: "{{ __result.json.access_token }}"

- name: "Test connection - get API version"
  ansible.builtin.uri:
    url: "https://console.redhat.com/api/image-builder/v1/version"
    method: "GET"
    headers:
      Authorization: "Bearer {{ __access_token }}"
      Content-Type: "application/json"
    body_format: "form-urlencoded"
    validate_certs: true
    return_content: true
  register: __result

- name: "Assert success"
  ansible.builtin.assert:
    that:
      - __result.json.version == "1.0"
