---
galaxy_info:
  author: Showroom Project Team
  description: This roles creates DNS zones and records in Microsoft Azure.
  company: Red Hat, Inc.
  license: GPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags: []
dependencies: []
collections:
  - azure.azcollection
