---
azure_vm_deploy_public_ip_allocation_method: "static"
azure_vm_deploy_vm_size: "Standard_B4ms"
azure_vm_deploy_image_name: "image-rhel-94"
azure_vm_deploy_user: "{{ vm_user }}"
azure_vm_deploy_user_public_key: "{{ vm_user_public_key }}"
azure_vm_deploy_tags: "{{ vm_tags }}"
