---
- name: Manage VNet Peering
  azure.azcollection.azure_rm_virtualnetworkpeering:
    subscription_id: "{{ vnet_peer_var.azure_subs | default(omit) }}"
    tenant: "{{ azure_tenant_id | default(omit) }}"
    client_id: "{{ techuser_ansible_client_id | default(omit) }}"
    secret: "{{ techuser_ansible_secret_value | default(omit) }}"
    state: "{{ azure_network_vnet_peering_state }}"
    resource_group: "{{ vnet_peer_var.azure_rg | default(omit) }}"
    virtual_network: "{{ vnet_peer_var.azure_vnet | default(omit) }}"
    name: "{{ vnet_peer_var.azure_vnet_peer | default(omit) }}"
    remote_virtual_network: "/subscriptions/{{ azure_subscription_id }}/resourceGroups/\
      {{ azure_rg }}/providers/Microsoft.Network/virtualNetworks/{{ azure_vnet }}"
    allow_virtual_network_access: "{{ azure_network_allow_virtual_network_access }}"
    allow_forwarded_traffic: "{{ azure_network_allow_forwarded_traffic }}"

- name: Manage VNet Peering
  azure.azcollection.azure_rm_virtualnetworkpeering:
    subscription_id: "{{ azure_subscription_id | default(omit) }}"
    tenant: "{{ azure_tenant_id | default(omit) }}"
    client_id: "{{ techuser_ansible_client_id | default(omit) }}"
    secret: "{{ techuser_ansible_secret_value | default(omit) }}"
    state: "{{ azure_network_vnet_peering_state }}"
    resource_group: "{{ azure_rg | default(omit) }}"
    virtual_network: "{{ azure_vnet | default(omit) }}"
    name: "{{ vnet_peer_var.azure_vnet_peer | default(omit) }}"
    remote_virtual_network: "{{ vnet_peer_var.azure_vnet_id | default(omit) }}"
    allow_virtual_network_access: "{{ azure_network_allow_virtual_network_access }}"
    allow_forwarded_traffic: "{{ azure_network_allow_forwarded_traffic }}"
